# compose 파일 버전
version: "3"
services:
  # 서비스 명
  authorization-service:
    # 사용할 이미지
    image: hybriddevslim/authorization-server-2023:latest
    # 컨테이너 실행 시 재시작
    restart: always
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    expose:
      - "9090"
    env_file:
      - authorization-service.env
    # 볼륨 설정
    volumes:
      - ./data/authorization/:/data
  # 서비스 명
  member-service:
    # 사용할 이미지
    image: hybriddevslim/member-service-2023:latest
    restart: always
    expose:
      - "8080"
    env_file:
      - member-service.env
    # 볼륨 설정
    volumes:
      - ./data/member_service/:/data
  # 서비스 명
  message-service:
    # 사용할 이미지
    image: hybriddevslim/message-service-2023:latest
    restart: always
    expose:
      - "8080"
    env_file:
      - message-service.env
    # 볼륨 설정
    volumes:
      - ./data/message_service/:/data
  # 서비스 명
  talk-client-service:
    # 사용할 이미지
    image: hybriddevslim/talk-client-server-2023:latest
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - talk-client-service.env
    # 볼륨 설정
    volumes:
      - ./data/talk-client-service/:/data
  # 서비스 명
  postgresql:
    # 사용할 이미지
    image: postgres:latest
    # 컨테이너 실행 시 재시작
    restart: always
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "5432:5432"
    # 환경 변수 설정
    environment:
      # PostgreSQL 계정 및 패스워드 설정 옵션
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    # 볼륨 설정
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
      - ./conf/postgresql/:/docker-entrypoint-initdb.d
  # 서비스 명
  mongo:
    # 사용할 이미지
    image: mongo:latest
    container_name: mongo
    # 컨테이너 실행 시 재시작
    restart: always
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "27017:27017"
    # 환경 변수 설정
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    healthcheck:
      test: ["CMD-SHELL", "sh -c /scripts/rs-init.sh"]
      interval: 20s
    # 볼륨 설정
    volumes:
      - ./data/mongo/:/var/lib/mongo/data
      - ./conf/mongo/replica.sh:/scripts/rs-init.sh
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis/:/data
      - ./conf/redis.conf:/usr/local/conf/redis.conf
    command: redis-server /usr/local/conf/redis.conf
  resource-service:
    image: "nginx"
    restart: always
    ports:
      - "5002:5002"
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf